### PR TITLE
Fixing and enhancing resistor

### PR DESCRIPTION
**Pull request by marcin-golebiowski**

### CODE REVIEW

**Comment by marcin-golebiowski** [comment]
@svenboulanger Please take at the tests and verify that I understand resistor syntax.

**Comment by marcin-golebiowski** [comment]
@svenboulanger If we want to support netlists from PSpice then I think we need to support that syntax where you define TC1/TC2 on resistor.  A lot of netlists have that.

I'm not sure if you need to change Spice#. The tests are passing now :)
The Resistor model is created internally and then TC1, TC2 parameters  are set on that model.

**Comment by svenboulanger** [comment]
Does it also handle the TC parameters on the model correctly? PSpice documentation says that model parameters are preferred over in-line.

To me that doesn't make much sense though... But if it's true, then you're right in that it isn't needed in the core library. I would like to see additional tests with TC on models though.

**Comment by marcin-golebiowski** [comment]
@svenboulanger Are you sure that  model parameters are preferred over in-line (on resistor)? the opposite makes more sense

**Comment by svenboulanger** [comment]
I agree, but that is what I found in the online manual. I have no way to verify it.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  OK. I've found it too... I will implement it in that way.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Please take a look so I can merge to development. I will work today also on TCE parameter ...

**Pull request merged**
