### PR TITLE
Uniform, gauss distribution, update to Spice# 2.7.3, fix with negative operator

### PR DESCRIPTION
**Pull request by marcin-golebiowski**

### CODE REVIEW

**Comment by svenboulanger** [comment]
Out of interest: what was the problem with the static operator?

**Comment by marcin-golebiowski** [comment]
@svenboulanger That static operator shouldn't be static because it's modified in the constructor of SpiceExpressionParser

**Comment by svenboulanger** [comment]
Why is the negation operator sometimes made left-associative?

**Comment by marcin-golebiowski** [comment]
@svenboulanger In LTSpice it's, according to documentation that I've found.

**Comment by svenboulanger** [comment]
It sounds a bit strange to me (it doesn't make sense for a prefix unary operator to be left-associative). But I can't find anything about operators for LTSpice so I have no way of making sure...

**Comment by marcin-golebiowski** [comment]
@svenboulanger I think I found something about it some time ago but I will double check it later today. Thanks.

**Comment by marcin-golebiowski** [comment]
If found something about `**` infix operator in LtSpice documentation (in section about .PARAM dot statement):

"Raise left hand side to power of right hand side, only real part is returned,  e.g., -2**1.5 returns zero, not 2.82843i"

What do you think?

**Comment by svenboulanger** [comment]
It seems to me that the power operator has a smaller precedence than unary negation, but associativity doesn't seem to be affected here.

**Pull request merged**
